# Use an official Nginx image as a base
FROM nginx:latest

# Copy website files to the container
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]