- name: Build and Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:

    - name: Stopping the Container
      docker_container:
        name: hightech-container
        image: hightech:latest
        state: stopped

    - name: Removing the Container
      docker_container:
        name: hightech-container
        image: hightech:latest
        state: absent

    - name: Removing Docker Image
      docker_image:
        name: hightech:latest
        state: absent


    - name: Building Docker Image
      docker_image:
        name: hightech:latest
        source: build
        build:
          path: ~/project/